<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4kp4p7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4kp4p7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE4kp4p7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE4kp4p7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerE4kp4p7\appDevDebugProjectContainer(array(
    'container.build_hash' => 'E4kp4p7',
    'container.build_id' => 'f4dbd2af',
    'container.build_time' => 1519719971,
));
