<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR4vtznh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR4vtznh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerR4vtznh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerR4vtznh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerR4vtznh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'R4vtznh',
    'container.build_id' => '3a28e9e8',
    'container.build_time' => 1519400573,
));
