<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHapso5o\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHapso5o/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHapso5o.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHapso5o\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHapso5o\appProdProjectContainer(array(
    'container.build_hash' => 'Hapso5o',
    'container.build_id' => '9f544c01',
    'container.build_time' => 1519031096,
));
